### PR TITLE
ISSUE-959 DO NOT run Javadoc generation as part of install

### PR DESCRIPTION
**Pull request by lewismc**
This issue allows a local developer (me :) ) to build the project!

Documented in #959

### CODE REVIEW

**Comment by lewismc** [comment]
I do not like commenting out code... please advise how this should be implemented for this project. Thank you

**Comment by lewismc** [comment]
I literally cannot build the project without this **fix**.

**Comment by ignazio1977** [comment]
Have you tried associating it to the deploy phase rather than the package phase? I'd expect that to do the trick. Otherwise we should remove the phase annotation and play around to make sure the javadoc are generated before the signatures are generated.

-- build systems are the worst except for all the alternatives

**Comment by lewismc** [comment]
> Have you tried associating it to the deploy phase rather than the package phase?

No... I just tried to install!

> I'd expect that to do the trick.


That's not in any README therefore it is not assumed. I would like to try and make this project more developer friendly.

Just to be clear... I cannot even build the project in its current state. 

> -- build systems are the worst except for all the alternatives

Let's agree to disagree... we should at least be able to build the project. Right now I cannot.

**Comment by ignazio1977** [comment]
> Let's agree to disagree

It was a joke... Anyway.

Not sure why the build doesn't work on Java 8, that's what I use to build version 4 and 5.

There's a switch in the main pom. Set <no-javadoc>false</no-javadoc> to <no-javadoc>true</no-javadoc>, it will skip javadoc generation.

**Comment by ignazio1977** [comment]
ff84f153f89619a192c71e888c2114956a1ebaae should resolve this problem. It also moves the version to 5.1.16-SNAPSHOT.

**Comment by lewismc** [comment]
Thanks @ignazio1977

**Pull request closed without merging**
