### PR TITLE
Update Examples.java

### PR DESCRIPTION
**Pull request by RadW2020**
I think  a DataFactory object is needed here

### CODE REVIEW

**Comment by RadW2020** [comment]
mmm sorry I missed that. 
I thought this was an stand alone file like this one [link](https://github.com/RadW2020/owl-api/blob/master/contract/src/test/java/org/coode/owlapi/examples/Examples.java)

**Comment by ignazio1977** [comment]
I'm happy for a change like that to help with readabilty of the example, but the variable should be named to not conflict with the existing one. Otherwise it will just cause Eclipse to annoy me with warnings :-)

**Comment by RadW2020** [comment]
I think it is a good a idea to have a stand-alone example file for those who get first contact with this project. 
If you like this idea I can work on it.

**Comment by ignazio1977** [comment]
Contributions always welcome!

**Comment by ignazio1977** [comment]
Merged

**Pull request closed without merging**
