### PR TITLE
OSGI Integration Test, and fixes so it can pass

### PR DESCRIPTION
**Pull request by sesuncedu**
There are certain things even John Austin couldn't do with words.  
One of them is express quite how much I hate OSGI right now.  

Actual info in commit messages and diffs.  Except for the missing 'not' in 'not as keen'.

### CODE REVIEW

**Comment by sesuncedu** [comment]
There was a Roundtripping test failure on the last commit that went away whilst I looked a travis ; I think there's probably race conditions still.

Also: 
https://github.com/ops4j/peaberry/wiki/Peaberry-Activation-Guide

**Comment by sesuncedu** [comment]
Tests in error: 
  PrimerOWLXMLRoundTrippingTestCase>AbstractRoundTrippingTestCase.testManchesterOWLSyntax:80->TestBase.roundTripOntology:440->TestBase.equal:140 » IllegalArgument

**Comment by ignazio1977** [comment]
You and me both. I was trying to do a release yesterday but the way the testsupport module is wired in is not liked by Nexus. Ah well.

**Comment by ignazio1977** [comment]
I've merged this. No exceptions locally, we'll see what Travis says

**Pull request closed without merging**
