### PR TITLE
Upgraded to RDF4j 3.7.4 and fixed issues with OSGi bundles

### PR DESCRIPTION
**Pull request by daltontc**
- Upgraded to latest RDF4j version (3.7.4)
- Fixed OSGi bundle import version issue where it was requiring 2.x version of RDF4j

### CODE REVIEW

**Comment by daltontc** [comment]
The current RDF4j version limiter in the OSGi distribution makes OWLAPI unable to run in an OSGi with the proper 3.x version. Currently is requiring a 2.x version that OWLAPI is not even using.

**Comment by daltontc** [comment]
RDF4j 3.5.0 broke out the `rdf4j-model` dependency into 3 `rdf4j-model`, `rdf4j-model-api`, and `rdf4j-model-vocabulary`. New dependencies needed to be added for OSGi compatibility.

See https://rdf4j.org/release-notes/3.5.0/

**Comment by daltontc** [comment]
@ignazio1977 any chance you can review this PR?

**Comment by ignazio1977** [comment]
Sorry, haven't had a chance to look at the patch set in detail yet. Looks
good, I plan to merge it as soon as I can check it out properly.

**Comment by daltontc** [comment]
Just curious @ignazio1977 , what is your release cycle / when could I expect to be able to pull down these changes?

**Comment by ignazio1977** [comment]
There isn't a tightly defined release cycle, I make a release when there's a significant number of changes/bug fixes or there's an urgent need for one of them

**Pull request merged**
