### PR TITLE
Ability to follow multiple HTTP redirects when loading ontologies

### PR DESCRIPTION
**Pull request by ventuc**
Fix for issue #954

### CODE REVIEW

**Comment by lewismc** [comment]
Do you have a test case @ventuc ? It would help to prove the case. Offhand, I personally cannot reproduce this use case... BUT, I think I have experienced it in the past! A test would help so much.

**Comment by ventuc** [comment]
Hi @lewismc,

I don't really have a test case. I made a simple test only to reproduce the bug. At the moment, I get it only when loading Dublic Core.

Without this fix, the following test fails because the document retrieved is not the RDF/XML ontology but an HTML document telling to see another URL.


```java
OWLOntologyLoaderConfiguration config = new OWLOntologyLoaderConfiguration();
config.setFollowRedirects(true);

Optional<InputStream> ontologyStream = DocumentSources.getInputStream(IRI.create("http://purl.org/dc/elements/1.1/"), config, "application/rdf+xml");
assertTrue(ontologyStream.isPresent());
StringWriter sw = new StringWriter();
IOUtils.copy(ontologyStream.get(), sw, StandardCharsets.UTF_8);
String ontology = sw.toString();

assertTrue(ontology.startsWith("<?xml"));
```

**Comment by ignazio1977** [comment]
Cheers @ventuc, I'm trying to figure out the implications of the change, looks correct but I haven't wrapped my head around possible consequences of the cycle yet.

**Comment by ventuc** [comment]
Thanks! I hope you can merge this fix as soon as possible, as for now we're stuck for being not able to import Dublin Core...

**Comment by ignazio1977** [comment]
I found a simpler change that passes the test.
The method was meant to call itself with a rebuilt connection if a redirect http status was found; it instead just rebuilt the connection - so, it follows redirects only once, while it should do so multiple times, until a non redirect URL is found.

However, we also need to keep track of visited URLs. Otherwise a scenario where URL A redirects to URL B and URL B redirects to A would lead to an infinite recursion (or an infinite loop depending on implementation.

**Comment by ventuc** [comment]
Ok, good!
So, should I close this pull request? When are you planning to release the fix? Thank you!

**Comment by ignazio1977** [comment]
Clearing out some javadoc, in a few days.

**Pull request closed without merging**
