### PR TITLE
RDF-1.1 and Sesame-4 targeted at OWLAPI-5

### PR DESCRIPTION
**Pull request by ansell**
This pull request is a rebase of pull request #218 that has been updated to use Sesame-4 that was recently released, and targeted at OWLAPI-5 instead of version 4.

There are quite a few warnings, and one failed test, which I need someone else to look at as I don't understand what the warnings are for, and I am not sure how to fix the test. The details for the failing test and the warnings are in the TravisCI logs for the last build.

### CODE REVIEW

**Comment by ignazio1977** [comment]
Thanks, I'll work on merging this asap

**Comment by ansell** [comment]
It may be useful to add the following test back into the new round tripping test structure. I have not been active on the codebase for a while so I wasn't sure what the replacement for AbstractAxiomsRoundTrippingTestCase was so I removed it temporarily to get the code to compile:

     @Override
     protected Set<? extends OWLAxiom> createAxioms() {
        OWLLiteral literalWithLang = Literal("abc", "en");
        OWLLiteral literalWithoutLang = Literal("abcd", "");
        OWLLiteral literalPlain = Literal("abcde");
        OWLLiteral literalString = Literal("abcdef", OWL2Datatype.XSD_STRING);
        OWLClass cls = Class(iri("A"));
        OWLAnnotationProperty prop = AnnotationProperty(iri("prop"));
        OWLAnnotationAssertionAxiom ax1 = AnnotationAssertion(prop,
                cls.getIRI(), literalWithLang);
        OWLAnnotationAssertionAxiom ax2 = AnnotationAssertion(prop,
                cls.getIRI(), literalWithoutLang);
        OWLAnnotationAssertionAxiom ax3 = AnnotationAssertion(prop,
                cls.getIRI(), literalPlain);
        OWLAnnotationAssertionAxiom ax4 = AnnotationAssertion(prop,
                cls.getIRI(), literalString);
        Set<OWLAxiom> axioms = new HashSet<>();
        axioms.add(ax1);
        axioms.add(ax2);
        axioms.add(ax3);
        axioms.add(ax4);
        axioms.add(Declaration(cls));
        return axioms;
     }

**Comment by ignazio1977** [comment]
Test added back in fc0f8cdcc48f47953bc8f14f58f9a1182a5f3920

Cherry picked, fixed the broken tests, pushed.

**Comment by ansell** [comment]
Thanks!

**Pull request closed without merging**
